### ISSUE TITLE
Please tell me about unknown errors.

### ISSUE THREAD

**Issue by ramd** [strategyengine/fsedistributionservice#12]
Even if I enter the parameters correctly, I get the following error
Do you know the cause?

 **ERROR 1 --- [nio-8080-exec-5] c.s.x.f.c.xrp.XrplClientServiceImpl      : Error sending payment to addressr....**
**java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 29**

------------------------------------

curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{
  "amount": "2",
  "currencyName": "CSC",
  "fromClassicAddress": "rEvs...",
  "fromPrivateKey": "s...",
  "fromSigningPublicKey": "021...B5528",
  "toClassicAddresses": [
    "r...",
    "r..."
  ],
  "trustlineIssuerClassicAddress": "rCSCManTZ8ME9EoLrSHHYKW8PPwWMgkwr"
}' 'http://localhost:8080/api/payment'

---------------------------------------
**Response Code:200**
**Response Body**
{
  "responseMessages": [
    "FAILED to pay r...",
    "FAILED to pay r..."
  ]
}

**Comment by barryrknapp** [comment]
Your private key looks incorrect.  It should start with ED......

If you get the latest code I've added quite a bit of documentation to the swagger page.
